{{- if and .Values.namespace.create (ne .Values.namespace.name .Release.Namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: headscale-demo-services
    {{- include "headscale-demo-services.partOf" . | nindent 4 }}
  {{- include "headscale-demo-services.keepAnnotations" . | nindent 2 }}
{{- end }}
