{{- if and .Values.namespace.create (ne (include "headscale-demo-services.ns" .) .Release.Namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "headscale-demo-services.ns" . }}
  labels:
    app.kubernetes.io/name: headscale-demo-services
    {{- include "headscale-demo-services.partOf" . | nindent 4 }}
  {{- include "headscale-demo-services.keepAnnotations" . | nindent 2 }}
{{- end }}
